
const data = [
    {
        "_id": "65218518b30b089e70cd79dd",
        "name": "Pratham Rajbhoj",
        "email": "rajbhojpr@rknec.edu",
        "password": "Pratham23",
        "codechef_id": "noob_pratham",
        "codeforces_id": "noob_pratham23",
        "leetcode_id": "noob_pratham23",
        "github_id": "Pratham2301",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-07T16:19:36.862Z",
        "__v": 0,
        "emailVerificationOTP": "7109",
        "emailVerificationOTPExpiry": "2023-10-07T17:36:04.421Z",
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65218525b30b089e70cd79df",
        "name": "Kush Munot",
        "email": "munotkg@rknec.edu",
        "password": "password",
        "codechef_id": "kushmunot",
        "codeforces_id": "axelblaze_17",
        "leetcode_id": "user4382M",
        "github_id": "Kush-munot",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-07T16:19:49.861Z",
        "__v": 0,
        "emailVerificationOTP": "7872",
        "emailVerificationOTPExpiry": "2023-10-07T17:50:53.270Z",
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6521852fb30b089e70cd79e1",
        "name": "Bhushan Wanjari",
        "email": "wanjaribl@rknec.edu",
        "password": "Bhushan21z@",
        "codechef_id": "bhushan_21z",
        "codeforces_id": "bhushanwanjari21z",
        "leetcode_id": "bhushan_cd",
        "github_id": "Bhushan21z",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-07T16:19:59.362Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65218539b30b089e70cd79e3",
        "name": "Madhav Jha",
        "email": "jhamd@rknec.edu",
        "password": "coderz@1234",
        "codechef_id": "jhamadhav28",
        "codeforces_id": "jhamadhav",
        "leetcode_id": "jhamadhav",
        "github_id": "jhamadhav",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-07T16:20:09.161Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6522bc399c037a72294c5809",
        "name": "Pravin nandankar",
        "email": "nandankarps@rknec.edu",
        "password": "Pravin916",
        "codechef_id": "pravin916",
        "codeforces_id": "Pravin-nandankar",
        "leetcode_id": "Pravin_Nandankar",
        "github_id": "pravin435916",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-08T14:27:05.822Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6522c0499c037a72294c5862",
        "name": "Priya Chaurasiya",
        "email": "chaurasiyaps@rknec.edu",
        "password": "Quinell@43",
        "codechef_id": "quinella",
        "codeforces_id": "chaurasiyaps",
        "leetcode_id": "priyachaurasiyaa",
        "github_id": "priyachau12",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-08T14:44:25.739Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65240dabcd53807fb2eb18ba",
        "name": "Abhash Goyal",
        "email": "goyalar@rknec.edu",
        "password": "jaishreeram",
        "codechef_id": "abhash_goyal",
        "codeforces_id": "abhash_goyal",
        "leetcode_id": "abhash_18",
        "github_id": "abhashgoyal",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-09T14:26:51.155Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652411f4cd53807fb2eb1a91",
        "name": "Poushik Yelne",
        "email": "yelneps@rknec.edu",
        "password": "Poushik@11",
        "codechef_id": "poushik11",
        "codeforces_id": "poushikyelne750",
        "leetcode_id": "poushik",
        "github_id": "Poushik11",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-09T14:45:08.251Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524152ccd53807fb2eb1b21",
        "name": "Lakshay bogal",
        "email": "bogalld@rknec.edu",
        "password": "rajputbogal",
        "codechef_id": "ranger_1",
        "codeforces_id": "Lakshaybogal",
        "leetcode_id": "Lakshaybogal",
        "github_id": "lakshaybogal",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-09T14:58:52.274Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65242c38cd53807fb2eb1f60",
        "name": "Prathamesh",
        "email": "gujarpa@rknec.edu",
        "password": "Gujar16_03",
        "codechef_id": "gujar16_03",
        "codeforces_id": "gujar",
        "leetcode_id": "gujarpa",
        "github_id": "GujarPrathamesh16",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-09T16:37:12.527Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524323dcd53807fb2eb2178",
        "name": "Saket Rathi",
        "email": "rathisa_2@rknec.edu",
        "password": "coderz@icyshadow",
        "codechef_id": "devxicy",
        "codeforces_id": "devxicy",
        "leetcode_id": "devxicy",
        "github_id": "iceXshadow",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-09T17:02:53.558Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524bc6bf42c8f08d6593a59",
        "name": "Adesh Bode",
        "email": "bodead@rknec.edu",
        "password": "#@786god",
        "codechef_id": "adeshbode",
        "codeforces_id": "Adeesh-bode ",
        "leetcode_id": "adeshbode ",
        "github_id": "Adeesh-bode",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T02:52:27.520Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524ca04487ef9c2efc504e3",
        "name": "Ishan Jabalpure",
        "email": "jabalpureid@rknec.edu",
        "password": "Idpjbl@2002",
        "codechef_id": "ishanjabalpure",
        "codeforces_id": "jabalpureishan",
        "leetcode_id": "jabalpureishan",
        "github_id": "jabalpureishan",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T03:50:28.092Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524cd0e487ef9c2efc50592",
        "name": "Yash Wankhedkar",
        "email": "wankhedkaryn@rknec.edu",
        "password": "P0kem0n1o1#43",
        "codechef_id": "bigdwarf43",
        "codeforces_id": "Bigdwarf",
        "leetcode_id": "bigdwarf43",
        "github_id": "bigdwarf43",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T04:03:26.560Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6524cd90487ef9c2efc50633",
        "name": "Aakhyan Jeyush",
        "email": "jeyushas@rknec.edu",
        "password": "aakhyan2005",
        "codechef_id": "evolutionx10",
        "codeforces_id": "evolutionx",
        "leetcode_id": "evolutionx",
        "github_id": "EvolutionX-10",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T04:05:36.488Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65250954b5b0c02e6a2f7f44",
        "name": "Mayur Kawale",
        "email": "kawalemn_1@rknec.edu",
        "password": "Mayur#2004",
        "codechef_id": "mefisto04",
        "codeforces_id": "mefisto04",
        "leetcode_id": "mefisto_04",
        "github_id": "Mefisto04",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T08:20:36.685Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65253407ac2ef68c93d8cde8",
        "name": "Ariyaan Khurram",
        "email": "khurrama@rknec.edu",
        "password": "ariyaancoder",
        "codechef_id": "ariyaan123",
        "codeforces_id": "Ariyaan",
        "leetcode_id": "NA",
        "github_id": "ariyaan321",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T11:22:47.334Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525494de5a0ec8059768a76",
        "name": "Apeksha Jamjar",
        "email": "jamjaran@rknec.edu",
        "password": "Apeksha@2005",
        "codechef_id": "apekshaj04",
        "codeforces_id": "apekshaj04",
        "leetcode_id": "apekshaj04",
        "github_id": "Apekshaj04",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T12:53:33.946Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65254d50e5a0ec8059768ba6",
        "name": "Riya Jaiswal",
        "email": "jaiswalra@rknec.edu",
        "password": "@Riya221004",
        "codechef_id": "riyajaiswal22",
        "codeforces_id": "Riya_Jaiswal-22",
        "leetcode_id": "Riya_Jaiswal-22",
        "github_id": "Riya-Jaiswal22 ",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T13:10:40.419Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525557be5a0ec8059768c0c",
        "name": "Vibhanshu",
        "email": "dubeyvd_1@rknec.edu",
        "password": "@Vibhanshu18",
        "codechef_id": "vibhanshu_d",
        "codeforces_id": "dex_morgan",
        "leetcode_id": "vibhanshudubeyy",
        "github_id": "vibhanshudubeyy",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T13:45:31.178Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525589fe5a0ec8059768cfe",
        "name": "Harsh Tiwari",
        "email": "tiwarihs@rknec.edu",
        "password": "RcoemCoderz@2934",
        "codechef_id": "harshhtiwari",
        "codeforces_id": "harshhtiwari",
        "leetcode_id": "harshhtiwari",
        "github_id": "HarshhT29",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T13:58:55.289Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65256a60bbe4bf8889461941",
        "name": "varun",
        "email": "sukalkarvp@rknec.edu",
        "password": "Varun@#1",
        "codechef_id": "varun71",
        "codeforces_id": "varun_sukalkar",
        "leetcode_id": "varunsukalkar",
        "github_id": "varunsukalkar",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T15:14:40.456Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65256e1abbe4bf8889461cc4",
        "name": "Gaurav Kedia",
        "email": "kediagm@rknec.edu",
        "password": "Gaurav@2002",
        "codechef_id": "kedia_gaurav",
        "codeforces_id": "kedia_gaurav",
        "leetcode_id": "kedia_gaurav",
        "github_id": "GauravMKedia",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T15:30:34.740Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65257224bbe4bf8889461ff0",
        "name": "Krushna Dande",
        "email": "dandekr@rknec.edu",
        "password": "Onepunchman@",
        "codechef_id": "krushn_123",
        "codeforces_id": "krdande2",
        "leetcode_id": "krdande2",
        "github_id": "KrushnaD0",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T15:47:48.631Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65257520bbe4bf88894621b8",
        "name": "Mayank Jaiswal",
        "email": "jaiswalms_1@rknec.edu",
        "password": "Jaiswal@1971",
        "codechef_id": "mayank0104",
        "codeforces_id": "mayankjaiswal0104",
        "leetcode_id": "mayankjaiswal0104",
        "github_id": "mayankjaiswal27",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T16:00:32.392Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65257a3dbbe4bf88894624e5",
        "name": "Ekansh ",
        "email": "mahajaneh@rknec.edu",
        "password": "Mahajan@123",
        "codechef_id": "ekanshmahajan1",
        "codeforces_id": "3kAnsh",
        "leetcode_id": "ekanshmahajan1010",
        "github_id": "Ekansh10",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T16:22:21.888Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65258d146a4739293e0e214b",
        "name": "Arnav Kadoo",
        "email": "kaduan@rknec.edu",
        "password": "iamarnav",
        "codechef_id": "baba_yaga15",
        "codeforces_id": "mere_papa",
        "leetcode_id": "arnavkadoo",
        "github_id": "Arnav-Kadu",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T17:42:44.992Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525a4b94828d9e5fd89f1c1",
        "name": "Preet Mahadule",
        "email": "mahadulepb@rknec.edu",
        "password": "Preet_m29",
        "codechef_id": "preetmahadule",
        "codeforces_id": "Preet_M29",
        "leetcode_id": "Preet_M29",
        "github_id": "MPreet29",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-10T19:23:37.648Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525fc6840a5d16e82ea190b",
        "name": "Zeenat Sheikh",
        "email": "sheikhzp@rknec.edu",
        "password": "Zeenat#15",
        "codechef_id": "zeenat15",
        "codeforces_id": "sheikhzp_1",
        "leetcode_id": "ZeenatAD15",
        "github_id": "Zeenat15",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T01:37:44.713Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6525ff8c40a5d16e82ea1aea",
        "name": "Tushar Pamnani ",
        "email": "pamnanita@rknec.edu",
        "password": "sHriRCOEM",
        "codechef_id": "tushar59",
        "codeforces_id": "Tushar.A.Pamnani",
        "leetcode_id": "tusharpamnani55",
        "github_id": "tusharpamnani",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T01:51:08.056Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652604e040a5d16e82ea1c54",
        "name": "Ikshit Talera",
        "email": "taleraiy@rknec.edu",
        "password": "khuljasimsim@04",
        "codechef_id": "ikshit_04",
        "codeforces_id": "ikshit_04",
        "leetcode_id": "ikshit_04",
        "github_id": "ikshit264",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T02:13:52.094Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526081240a5d16e82ea1f90",
        "name": "Ayan",
        "email": "sheikhaa_3@rknec.edu",
        "password": "ARPT@#1234",
        "codechef_id": "ayan_sh03",
        "codeforces_id": "reckoner_003",
        "leetcode_id": "Ayan879",
        "github_id": "Ayan-sh03",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T02:27:30.165Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652611b6de9eaf8a3e33074a",
        "name": "Aayush Pandey",
        "email": "pandeyaa_1@rknec.edu",
        "password": "hackerdada#135",
        "codechef_id": "aayush_pandey",
        "codeforces_id": "Aayush_pandey12",
        "leetcode_id": "AayushPandey",
        "github_id": "Aayush1357",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T03:08:38.687Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652617bbde9eaf8a3e330b7d",
        "name": "Rohit Bhojwani",
        "email": "bhojwanirs@rknec.edu",
        "password": "RohitBhojwani1@",
        "codechef_id": "mackrohit",
        "codeforces_id": "SpoilrdBratt",
        "leetcode_id": "rbbhojwani123",
        "github_id": "Rohitbhojwani",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T03:34:19.540Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652619a8de9eaf8a3e330ea4",
        "name": "Anup Dhoble",
        "email": "dhobleaa@rknec.edu",
        "password": "c8KRV4.tjfELHwU",
        "codechef_id": "dfasdfad",
        "codeforces_id": "adffda",
        "leetcode_id": "sdfadfafa",
        "github_id": "dfsadf",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T03:42:32.489Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65262b7438adc1975b410a8e",
        "name": "Anish Wairagade ",
        "email": "wairagadear@rknec.edu",
        "password": "ani12345",
        "codechef_id": "anishwairagade44@gmail.com",
        "codeforces_id": "wairagadear",
        "leetcode_id": "anish1699",
        "github_id": "anish1699",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T04:58:28.238Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "652654eb655140fa29ecb8be",
        "name": "Manas Saha ",
        "email": "sahamm@rknec.edu",
        "password": "Manas@1511200",
        "codechef_id": "manas_saha883",
        "codeforces_id": "Manas421321",
        "leetcode_id": "manas_88",
        "github_id": "Manas8803",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T07:55:23.895Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65267d6c2cbcb505d5a44bb2",
        "name": "Shreyash Kathane ",
        "email": "kathanesu@rknec.edu",
        "password": "Shreyash@123#.",
        "codechef_id": "shreyashkathan",
        "codeforces_id": "shreyashk07",
        "leetcode_id": "SHREYASH_KATHANE2004",
        "github_id": "Shreyash077",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T10:48:12.853Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "65269ff5104a05998f605cbb",
        "name": "Aishwarya Tatiwar",
        "email": "tatiwarav@rknec.edu",
        "password": "Aish@#2004",
        "codechef_id": "aishwaryat22",
        "codeforces_id": "aishwaryat22",
        "leetcode_id": "aishwaryat22",
        "github_id": "AishwaryaTatiwar",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T13:15:33.817Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526ad408be53f6a5ca10432",
        "name": "Suyog Parkhi",
        "email": "parkhism@rknec.edu",
        "password": "Suyog@1503",
        "codechef_id": "suyog06",
        "codeforces_id": "suyogparkhi",
        "leetcode_id": "suyogp123456789",
        "github_id": "suyogparkhi",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T14:12:16.352Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526d48741e07b2e1689ff64",
        "name": "pranaymantri16",
        "email": "mantripp_1@rknec.edu",
        "password": "Pp16Mm13",
        "codechef_id": "pranaymantri16",
        "codeforces_id": "pranaymantri16",
        "leetcode_id": "pranaymantri16",
        "github_id": "pranaymantri16",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T16:59:51.162Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526d51941e07b2e168a00b8",
        "name": "Manan Maheshwari ",
        "email": "maheshwarimm@rknec.edu",
        "password": "Manan@221104",
        "codechef_id": "maheshwarimm",
        "codeforces_id": "maheshwarimm",
        "leetcode_id": "maheshwarimm",
        "github_id": "mananmaheshwari11",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T17:02:17.395Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526db3d41e07b2e168a044b",
        "name": "Shrujan kharwadey ",
        "email": "Kharwadeyss@rknec.edu",
        "password": "Shrujan@2004",
        "codechef_id": "rockstar_shru",
        "codeforces_id": "bossshrujan",
        "leetcode_id": "Shrujan Kharwadey",
        "github_id": "Unearthly-2004",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T17:28:29.474Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526dc0e41e07b2e168a05b1",
        "name": "Tanisha Avinash Bharvesh",
        "email": "bharveshta@rknec.edu",
        "password": "Tab04082003@",
        "codechef_id": "tanisha_1480",
        "codeforces_id": "tanisha.bharvesh",
        "leetcode_id": " Tbharvesh",
        "github_id": "Tbharvesh",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T17:31:58.389Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526dd3b41e07b2e168a07cf",
        "name": "Shreya Dhanuka ",
        "email": "dhanukasa@rknec.edu",
        "password": "SHreya&890",
        "codechef_id": "shreyaa08",
        "codeforces_id": "dhanukasa",
        "leetcode_id": "dhanukas2004",
        "github_id": "shreyaadhanuka",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "avatar": "https://avatars.githubusercontent.com/u/146207981?v=4",
        "createdAt": "2023-10-11T17:36:59.042Z",
        "__v": 0,
        "college_name": "Shri Ramdeobaba College Of Engineering and Management"
    },
    {
        "_id": "6526e3e6d2243bd35441b6ca",
        "name": "Shreyash Shahu ",
        "email": "sahushreyash48@gmail.com",
        "password": "sss13579",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "shreyash_sahu1",
        "codeforces_id": "1-Shreyash",
        "leetcode_id": "ShreyashShahu",
        "github_id": "1-Shreyash",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-11T18:05:26.512Z",
        "__v": 0
    },
    {
        "_id": "65270523c54de9cf518bf2c4",
        "name": "Anuj",
        "email": "anujjadhav0215@gmail.com",
        "password": "CodeCode@123",
        "college_name": "National Institute of Technology Patna",
        "codechef_id": "anujjadhav",
        "codeforces_id": "anujjadhav0215",
        "leetcode_id": "AnujJadhav",
        "github_id": "anuj1511",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-11T20:27:15.977Z",
        "__v": 0
    },
    {
        "_id": "65273b267b031ac55a566287",
        "name": "Aditya Pande",
        "email": "adityaspande1@gmail.com",
        "password": "adityar013",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "adityaspande1",
        "codeforces_id": "Adityapande1",
        "leetcode_id": "adityapande1",
        "github_id": "adityaspande1",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T00:17:42.121Z",
        "__v": 0
    },
    {
        "_id": "65274180be1993c5341a0c99",
        "name": "Parth Johri",
        "email": "parthjohri31@gmail.com",
        "password": "r568@",
        "college_name": "Delhi Technological University",
        "codechef_id": "parthjohri",
        "codeforces_id": "binarysolver",
        "leetcode_id": "binarysolver",
        "github_id": "ParthJohri",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T00:44:48.473Z",
        "__v": 0
    },
    {
        "_id": "652745e5be1993c5341a12b5",
        "name": "Prathamesh",
        "email": "bhujbal.prad@gmail.com",
        "password": "r34ddzGXipPyhDb",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "entei29",
        "codeforces_id": "entei29",
        "leetcode_id": "entei29",
        "github_id": "Prathameshbhujbal",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T01:03:33.950Z",
        "__v": 0
    },
    {
        "_id": "65276964e2904cefef72bdec",
        "name": "Shivam A Tadas",
        "email": "tadassa@rknec.edu",
        "password": "LastPassword26",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "tadasshivam10",
        "codeforces_id": "shivam-tadas-10",
        "leetcode_id": "shivam-tadas",
        "github_id": "shivam-tadas",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T03:35:00.382Z",
        "__v": 0
    },
    {
        "_id": "652776d4a8b409fc9e13cc2d",
        "name": "Rohit Chandak",
        "email": "chandakrd@rknec.edu",
        "password": "chandakrohit8",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "chandakrohit8",
        "codeforces_id": "chandakrohit08",
        "leetcode_id": "chandakrohit1",
        "github_id": "chandakrohit8",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T04:32:20.756Z",
        "__v": 0
    },
    {
        "_id": "652794c23d4b98ad8ec7aa44",
        "name": "Karan Kumbhar",
        "email": "karansunilk@iitbhilai.ac.in",
        "password": "Karan@123",
        "college_name": "Indian Institute of Technology Bhilai",
        "codechef_id": "karankumbhar09",
        "codeforces_id": "karankumbhar09 ",
        "leetcode_id": "karankumbhar09",
        "github_id": "karankumbhar47 ",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T06:40:02.477Z",
        "__v": 0
    },
    {
        "_id": "65279c7c3d4b98ad8ec7b909",
        "name": "Antonio Colapso",
        "email": "antoniocodes119@gmail.com",
        "password": "Omm@prakash1",
        "college_name": "Indian Institute of Technology Bhilai",
        "codechef_id": "its_just_fun",
        "codeforces_id": "Antonio_Colapso_07",
        "leetcode_id": "Antonio_Colapso_07",
        "github_id": "Antoniocolapso",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T07:13:00.624Z",
        "__v": 0
    },
    {
        "_id": "6527fd7b0c9a47f992125bb8",
        "name": "Muskan Jaiswal",
        "email": "jaiswalmm@rknec.edu",
        "password": "Muskan@12",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "muskanj758",
        "codeforces_id": "muskan_jais",
        "leetcode_id": "muskanjais",
        "github_id": "muskanjais30",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T14:06:51.528Z",
        "__v": 0
    },
    {
        "_id": "652802430c9a47f9921276e8",
        "name": "Priyanshi",
        "email": "priyanshi091202@gmail.com",
        "password": "Mansi@123",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "priyanshi0912",
        "codeforces_id": "Priyanshi_0912",
        "leetcode_id": "Priyanshi_0912",
        "github_id": "Priyanshi0912",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T14:27:15.581Z",
        "__v": 0
    },
    {
        "_id": "652805030c9a47f9921287f0",
        "name": "Sujal Kesharwani",
        "email": "kesharwanisr_1@rknec.edu",
        "password": "ranking@rcoem",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "sujal30",
        "codeforces_id": "kesharwanisr_1",
        "leetcode_id": "sujalkesharwanileet_cpp1",
        "github_id": "Sujal-k",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T14:38:59.506Z",
        "__v": 0
    },
    {
        "_id": "652808f20c9a47f992128f05",
        "name": "Srishti Dubey ",
        "email": "dubeysrishti1806@gmail.com",
        "password": "Riya@2000",
        "college_name": "Rajalakshmi Engineering College",
        "codechef_id": "dubeysrishti18",
        "codeforces_id": "Srishti_18",
        "leetcode_id": "dubeysrishti1806",
        "github_id": "srishti-cell",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T14:55:46.762Z",
        "__v": 0
    },
    {
        "_id": "652811bf0c9a47f99212af59",
        "name": "Adwait Salankar",
        "email": "salankaras_1@rknec.edu",
        "password": "adwait@2626",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "adwaitsalankar",
        "codeforces_id": "salankaras_1",
        "leetcode_id": "Adwait_097",
        "github_id": "AdwaitSalankar",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T15:33:19.272Z",
        "__v": 0
    },
    {
        "_id": "652814f20c9a47f99212c717",
        "name": "Kunal Choure",
        "email": "chourekunal4@gmail.com",
        "password": "kkcytpe4",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "kunalchoure",
        "codeforces_id": "Kunal_choure",
        "leetcode_id": "KUNAL_CHOURE",
        "github_id": "KUNALCHOURE",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T15:46:58.008Z",
        "__v": 0
    },
    {
        "_id": "6528229e0c9a47f99212ed51",
        "name": "Sarthak Khutafale",
        "email": "sarthakkhutafale14@gmail.com",
        "password": "sarthak1234",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "sarthak3434",
        "codeforces_id": "SarthaK343434",
        "leetcode_id": "Sarthak_3434",
        "github_id": "Devoke03",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T16:45:18.622Z",
        "__v": 0
    },
    {
        "_id": "652823910c9a47f99212f322",
        "name": "Supraj",
        "email": "gijress@rknec.edu",
        "password": "Supraj@25",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "supraj_25",
        "codeforces_id": "Supraj_G",
        "leetcode_id": "Supraj_G",
        "github_id": "supraj221",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T16:49:21.869Z",
        "__v": 0
    },
    {
        "_id": "652828b30c9a47f992132065",
        "name": "Awadhesh Gosewade",
        "email": "awadheshkg64@gmail.com",
        "password": "Awadhesh",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "-",
        "codeforces_id": "-",
        "leetcode_id": "-",
        "github_id": "Awadhesh-G",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T17:11:15.751Z",
        "__v": 0
    },
    {
        "_id": "652832120c9a47f99213352f",
        "name": "Pankaj Dewhare",
        "email": "pdew2002@gmail.com",
        "password": "P@nk1976",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "Pank002",
        "codeforces_id": "PankD002",
        "leetcode_id": "PankuD0002",
        "github_id": "PankuD002",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T17:51:14.036Z",
        "__v": 0
    },
    {
        "_id": "65283a03747ad57da0c62caa",
        "name": "Prathamesh kurve",
        "email": "kurvep18@gmail.com",
        "password": "pi@31415926",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "kurvep08",
        "codeforces_id": "kurvep18",
        "leetcode_id": "kurve18p",
        "github_id": "Prathamesh314",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T18:25:07.257Z",
        "__v": 0
    },
    {
        "_id": "65283b16747ad57da0c63257",
        "name": "Pranav Rathi",
        "email": "rathipv_1@rknec.edu",
        "password": "Kenkaneki@330",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "rathi_pranav",
        "codeforces_id": "Pranav_Rathi",
        "leetcode_id": "rathipranav330",
        "github_id": "pvrPranavRathi",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-12T18:29:42.675Z",
        "__v": 0
    },
    {
        "_id": "6528ba2799ab4d9600ee5466",
        "name": "Kritika Bhattad",
        "email": "bhattadka@rknec.edu",
        "password": "kritika2003@#",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "kritikabhattad",
        "codeforces_id": "kritikabhattad",
        "leetcode_id": "kritikabhattad",
        "github_id": "bhattadka",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T03:31:51.283Z",
        "__v": 0
    },
    {
        "_id": "6528bfc799ab4d9600ee6f57",
        "name": "Vinay Tiwari",
        "email": "tiwarivh@rknec.edu",
        "password": "Hartrilal@#19!",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "vinay_tiwari",
        "codeforces_id": "vinay_tiwari",
        "leetcode_id": "vinay_tiwari",
        "github_id": "Vinaytiwari25",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T03:55:51.831Z",
        "__v": 0
    },
    {
        "_id": "6528c63d99ab4d9600ee77a8",
        "name": "Anuj Vijay Pophali",
        "email": "anujpophali@gmail.com",
        "password": "india@11",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "anujp_2002",
        "codeforces_id": "anujp_2002",
        "leetcode_id": "anujp_2002",
        "github_id": "anujpophali",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T04:23:25.318Z",
        "__v": 0
    },
    {
        "_id": "6528c9dd99ab4d9600ee9f0e",
        "name": "Pratham M",
        "email": "prathammaske1304@gmail.com",
        "password": "123pra",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "NA",
        "codeforces_id": "maskepr",
        "leetcode_id": "pratm1304",
        "github_id": "pratm1304",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T04:38:53.645Z",
        "__v": 0
    },
    {
        "_id": "6528cd2799ab4d9600eeabc1",
        "name": "Sopan Thakre",
        "email": "thakresopan72@gmail.com",
        "password": "HENK",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "sopanthakre72",
        "codeforces_id": "HENK",
        "leetcode_id": "thakresopan72",
        "github_id": "henk1729",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T04:52:55.984Z",
        "__v": 0
    },
    {
        "_id": "6528cf2a99ab4d9600eebe6c",
        "name": "Yash Gupta",
        "email": "yash42gupta@gmail.com",
        "password": "1425367980#Yg",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "yashg_2907",
        "codeforces_id": "YASHG_2907",
        "leetcode_id": "Yash_2907",
        "github_id": "Yash-2907",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T05:01:30.026Z",
        "__v": 0
    },
    {
        "_id": "6528ebad6d6e957161c98f03",
        "name": "Ayaan sheikh",
        "email": "Sheikhah@rknec.edu",
        "password": "ayaan1121",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "ayaansheikh",
        "codeforces_id": "Sheikhayaan",
        "leetcode_id": "Ayaansheikhh",
        "github_id": "Ayaan sheikh",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T07:03:09.673Z",
        "__v": 0
    },
    {
        "_id": "6528f9dd4e1c2a97e9eb14e1",
        "name": "Arnav Joglekar",
        "email": "joglekaran@rknec.edu",
        "password": "Arnu@0204",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "arnav_coder",
        "codeforces_id": "arnav0204",
        "leetcode_id": "joglekaran",
        "github_id": "Arnav0204",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T08:03:41.146Z",
        "__v": 0
    },
    {
        "_id": "652960795823bd0b637441a7",
        "name": "Silvi Gupta",
        "email": "gsilvi2203@gmail.com",
        "password": "silvi@indiancoderz123",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "guptasilvi22",
        "codeforces_id": "guptasilvi",
        "leetcode_id": "guptasilvi",
        "github_id": "silvi-12",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T15:21:29.151Z",
        "__v": 0
    },
    {
        "_id": "65296b15d3f8e1ef250c7152",
        "name": "Smit Khobragade",
        "email": "smitkbgd@gmail.com",
        "password": "Smit123456",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "smit_kbgd16",
        "codeforces_id": "Smit_kbgd",
        "leetcode_id": "smitkbgd",
        "github_id": "Smitkhobragade",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T16:06:45.898Z",
        "__v": 0
    },
    {
        "_id": "65296ca4d3f8e1ef250c7aa8",
        "name": "Sahil",
        "email": "sahilbanswani03@gmail.com",
        "password": "Sahil@7499",
        "college_name": "G. H. Raisoni College of Engineering, Nagpur",
        "codechef_id": "sahilbanswani",
        "codeforces_id": "sahilbanswani",
        "leetcode_id": "sahilbanswani",
        "github_id": "sahil-banswani",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-13T16:13:24.984Z",
        "__v": 0
    },
    {
        "_id": "652a368f0c9a7bfb0be4a586",
        "name": "NIkhil Nandanwar",
        "email": "nikhilnandanwar429@gmail.com",
        "password": "Kaash@2006",
        "college_name": "Yeshwantrao Chavan College of Engineering, Nagpur",
        "codechef_id": "nikhil_nandanw",
        "codeforces_id": "nikhil_nandanwar.429",
        "leetcode_id": "nikhilnandanwar429",
        "github_id": "nikhilnandanwar429",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-14T06:34:55.949Z",
        "__v": 0
    },
    {
        "_id": "652a9f7971c4acc3c3dbffd4",
        "name": "Mayur Nagardhane",
        "email": "mayurnagardhane389@gmail.com",
        "password": "Mayur@1234",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "mayur0828",
        "codeforces_id": "mayurnagardhane389",
        "leetcode_id": "Mayur_Nagardhane",
        "github_id": "Mayur0828",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-14T14:02:33.262Z",
        "__v": 0
    },
    {
        "_id": "652adde9c8ca93160fb06e21",
        "name": "Om Aryan",
        "email": "aryano@rknec.edu",
        "password": "h4ck5k",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "cyberpsych",
        "codeforces_id": "cyberpsych",
        "leetcode_id": "cyberpsych",
        "github_id": "cyberpsychofc",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-14T18:28:57.501Z",
        "__v": 0
    },
    {
        "_id": "652b768f1fd3d91e537c4b5d",
        "name": "Krutika Bhanarkar",
        "email": "krutikabhanarkar9@gmail.com",
        "password": "Pcc#1234",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "bhanarkarkr",
        "codeforces_id": "bhanarkarkr",
        "leetcode_id": "bhanarkarkr",
        "github_id": "bhanarkarkr",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-15T05:20:15.443Z",
        "__v": 0
    },
    {
        "_id": "652b9950ea45d88de83df2f2",
        "name": "Naman Sarda",
        "email": "sardanh@rknec.edu",
        "password": "Naman@783",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "namansarda0708",
        "codeforces_id": "namansarda2007",
        "leetcode_id": "namansarda2007",
        "github_id": "NamanSarda",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-15T07:48:32.917Z",
        "__v": 0
    },
    {
        "_id": "652d1ad6aeea2d32b2f6d5ca",
        "name": "Tanish Agrawal",
        "email": "tanishagrawalofficial1@gmail.com",
        "password": "Tanish@78661660",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "tanish1660",
        "codeforces_id": "Agrawal_Tanish",
        "leetcode_id": "Tanish_Agrawal1508",
        "github_id": "Tanish1508",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-16T11:13:26.428Z",
        "__v": 0
    },
    {
        "_id": "65328a9567283ab8afd402ae",
        "name": "Emaan Javed",
        "email": "muhammadej@rknec.edu",
        "password": "Emaanezra75",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "E-maan",
        "codeforces_id": "E-man75",
        "leetcode_id": "E_maan75",
        "github_id": "E-maan",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-20T14:11:33.970Z",
        "__v": 0
    },
    {
        "_id": "6533e4a5beb03425159400c3",
        "name": "Chandaka Venkata Trinaine",
        "email": "chtrinaine@gmail.com",
        "password": "3naine052004",
        "college_name": "",
        "codechef_id": "chtrinaine",
        "codeforces_id": "trinainech",
        "leetcode_id": "chtrinaine052004",
        "github_id": "trinainech",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-21T14:48:05.280Z",
        "__v": 0
    },
    {
        "_id": "65341335ce26d650becf7673",
        "name": "Harsh Dakhare",
        "email": "hmdakhare1@gmail.com",
        "password": "hm@12345",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "harshdakhare",
        "codeforces_id": "harshdakhare",
        "leetcode_id": "hmdakhare1",
        "github_id": "Harshdakhare4",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-21T18:06:45.396Z",
        "__v": 0
    },
    {
        "_id": "6534a4e7cd64af532628e9e8",
        "name": "Ritik Chakravarti",
        "email": "ritikchakrawarti88@gmail.com",
        "password": "ritikchakravarti",
        "college_name": "Guru Nank Institute of Technology Nagpur",
        "codechef_id": "ritikchakravar",
        "codeforces_id": "ritik_chakravarti",
        "leetcode_id": "ritik_chakravarti",
        "github_id": "coderitik01",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-22T04:28:23.053Z",
        "__v": 0
    },
    {
        "_id": "65351796ec6d5cd861030fb5",
        "name": "Sujal Ravishankar Agrawal",
        "email": "sujalagrawalgondia@gmail.com",
        "password": "Sujal123@",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "sujal1885",
        "codeforces_id": "agrawalsr_14",
        "leetcode_id": "sujalagrawal1885",
        "github_id": "sujal1885",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-22T12:37:42.189Z",
        "__v": 0
    },
    {
        "_id": "65358066413ba96bc9278fa7",
        "name": "Suraj Verma",
        "email": "surajverma0347@gmail.com",
        "password": "Suraj@2580",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "NA",
        "codeforces_id": "NA",
        "leetcode_id": "NA",
        "github_id": "NA",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-22T20:04:54.368Z",
        "__v": 0
    },
    {
        "_id": "653a36254d9735defba4b8bb",
        "name": "Vedarth Ambilkar",
        "email": "vedarthambilkar2@gmail.com",
        "password": "vedarth@12042004",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "vedarth12",
        "codeforces_id": "Vedarth",
        "leetcode_id": "vedarth_1204",
        "github_id": "Vedarth1",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-26T09:49:25.424Z",
        "__v": 0
    },
    {
        "_id": "653a9ab6e555c22381508660",
        "name": "Vedant Shirbhate ",
        "email": "vedantshirbhate9@gmail.com",
        "password": "Vedu@007",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "captain_vs",
        "codeforces_id": "captain_vs",
        "leetcode_id": "vedantshirbhate9",
        "github_id": "vedantshirbhate1",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-26T16:58:30.483Z",
        "__v": 0
    },
    {
        "_id": "653b72c31ddb853908c83fff",
        "name": "Divy V. Purohit",
        "email": "divypurohit121@gmail.com",
        "password": "Luxmivilas123.",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "de14",
        "codeforces_id": "divy.purohit",
        "leetcode_id": "divypurohit",
        "github_id": "divypurohit",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-27T08:20:19.630Z",
        "__v": 0
    },
    {
        "_id": "653bfa5c02ab7668c90c1e0f",
        "name": "Prajwal Wandhare",
        "email": "prajwalwandhare100@gmail.com",
        "password": "Yoyohoney@990",
        "college_name": "Yeshwantrao Chavan College of Engineering, Nagpur",
        "codechef_id": "paju_980",
        "codeforces_id": "prajwalwandhare100",
        "leetcode_id": "prajwalwandhare100",
        "github_id": "paju_980",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-27T17:58:52.769Z",
        "__v": 0
    },
    {
        "_id": "653bfc8c02ab7668c90c2c7b",
        "name": "Kunal Dewangan",
        "email": "kunaldewangan1001@gmail.com",
        "password": "Kunal@DD1234",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "kunal_4530",
        "codeforces_id": "Kunal45",
        "leetcode_id": "Kunal4530",
        "github_id": "Kunal4530",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-27T18:08:12.289Z",
        "__v": 0
    },
    {
        "_id": "653bffa102ab7668c90c51fe",
        "name": "Janvi Sahu",
        "email": "sahujanvi317@gmail.com",
        "password": "J@nvi31",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "sahujanvi317",
        "codeforces_id": "sahujanvi317@gmail.com ",
        "leetcode_id": "janvisahu6604",
        "github_id": "Janvisahu31 ",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-27T18:21:21.352Z",
        "__v": 0
    },
    {
        "_id": "653de7d8badbf75908afa00d",
        "name": "Vedant Bhalerao",
        "email": "vedantbhalerao343@gmail.com",
        "password": "IAFvedz@4321",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "vedz_34",
        "codeforces_id": "Vedz_34",
        "leetcode_id": "vedz_34",
        "github_id": "vedz34",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-29T05:04:24.220Z",
        "__v": 0
    },
    {
        "_id": "6540fcd17f5d022991908de3",
        "name": "Rohit Patil",
        "email": "patilrp@rknec.edu",
        "password": "test123",
        "college_name": "Shri Ramdeobaba College of Engineering and Management",
        "codechef_id": "rohitpatil03",
        "codeforces_id": "hacker",
        "leetcode_id": "rohitpatil_03",
        "github_id": "rohitpatil03",
        "codechef_rating": 0,
        "codeforces_rating": 0,
        "leetcode_rating": 0,
        "total_score": 0,
        "createdAt": "2023-10-31T13:10:41.208Z",
        "__v": 0
    }
]

let namelist = []

for(let user of data){
    namelist.push(user.name)
}

console.log(namelist)

namelist.sort()

console.log(namelist)